version: "3"
    
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: foobar

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
